### ISSUE TITLE
Add torch-kbnufft 

### ISSUE THREAD

**Issue by paquiteau** [mind-inria/mri-nufft#101]
[torch-kbnufft](https://github.com/mmuckley/torchkbnufft) is used in the DL community. Yet better nufft libraries are available (e.g. cufinufft, gpunufft). The idea would be add torch-kbnufft in order to the run the benchmark, and show what is the best nufft currently. 

Note that torch-kbnufft has also some interesting capabilities, notably differentiation and support for toeplitz embedding (speeds things up in data consistency evaluation)

**Comment by Lenoush** [comment]
@paquiteau  can i close this ?

**Comment by chaithyagr** [comment]
Yes, thank you @Lenoush for all your updates and codes.
