### ISSUE TITLE
Missing file css_colors.txt

### ISSUE THREAD

**Issue by Daval-G** [mind-inria/mri-nufft#11]
After cloning & installing the current repository, I get the following error when trying to import the package as a whole:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/guillaume/miniconda3/envs/general/lib/python3.10/site-packages/mrinufft/__init__.py", line 9, in <module>
>     from .operators import (
>   File "/home/guillaume/miniconda3/envs/general/lib/python3.10/site-packages/mrinufft/operators/__init__.py", line 2, in <module>
>     from .interfaces import (
>   File "/home/guillaume/miniconda3/envs/general/lib/python3.10/site-packages/mrinufft/operators/interfaces/__init__.py", line 4, in <module>
>     from .cufinufft import MRICufiNUFFT, CUFINUFFT_AVAILABLE
>   File "/home/guillaume/miniconda3/envs/general/lib/python3.10/site-packages/mrinufft/operators/interfaces/cufinufft.py", line 8, in <module>
>     from .utils.gpu_utils import (
>   File "/home/guillaume/miniconda3/envs/general/lib/python3.10/site-packages/mrinufft/operators/interfaces/utils/__init__.py", line 7, in <module>
>     from .gpu_utils import (
>   File "/home/guillaume/miniconda3/envs/general/lib/python3.10/site-packages/mrinufft/operators/interfaces/utils/gpu_utils.py", line 53, in <module>
>     with open(str(Path(__file__).parent / "css_colors.txt")) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/guillaume/miniconda3/envs/general/lib/python3.10/site-packages/mrinufft/operators/interfaces/utils/css_colors.txt'
> 

I guess the `css_colors.txt` file was simply not pushed.

**Comment by paquiteau** [comment]
Yup It should be good now.

**Comment by chaithyagr** [comment]
Gosh i just love it when he just pushes to master directly, no PR nothing xD
