### ISSUE TITLE
Network issues in test-examples

### ISSUE THREAD

**Issue by alineyyy** [mind-inria/mri-nufft#123]
example_stacked.py and example_density.py can't pass in the test-examples because of some network connection errors.

Some alternatives should be purposed to solve these issues.

**Comment by paquiteau** [comment]
Well this is a bit tricky.

The only way I see for now is to propose to download image data from somewhere else than the brainweb dataset (using [brainweb_dl](https://github.com/paquiteau/brainweb_dl)  ) or we commit the image to the repo ( I am not for this, adding huge binary blob is not so good for git).

**Comment by paquiteau** [comment]
A solution might be to use the caching mechanism of github actions[^1]. The brainweb data is downloaded in ~/.cache/brainweb (or whatever is the environment variable $BRAINWEB_DIR) So we could setup a cache to both speed things up and make less call to download the phantoms.



[^1]: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by chaithyagr** [comment]
Thats a good idea.
