### ISSUE TITLE
Add case method == True in compute_density() in base.py

### ISSUE THREAD

**Issue by Lenoush** [mind-inria/mri-nufft#125]
here method can also be a bool : 
https://github.com/mind-inria/mri-nufft/blob/f5a6ba006184b96a1f73ff54be27d854797c79fe/src/mrinufft/operators/base.py#L323-L329

and here :
https://github.com/mind-inria/mri-nufft/blob/f5a6ba006184b96a1f73ff54be27d854797c79fe/src/mrinufft/operators/base.py#L334-L336
if method : 
    if nufft.cls has method pipe:
        method = "pipe"

**Comment by paquiteau** [comment]
Seems to be a reasonable addition, I guess you can handle it :)
