### ISSUE TITLE
Prevent saving temporary images on `/tmp` in examples

### ISSUE THREAD

**Issue by chaithyagr** [mind-inria/mri-nufft#170]
Saving temporarily on `/tmp` causes issues on local runners as some tasks seem to be deleting the files even before it is accessed, causing weird errors. @paquiteau I wonder if this is because the `shasum` is matching that from other examples?

**Comment by paquiteau** [comment]
that is very likely indeed, a solution would be to add some salt on the hash, aka a UNIX timestamp.
