### ISSUE TITLE
Add support to disable density compensation,

### ISSUE THREAD

**Issue by chaithyagr** [mind-inria/mri-nufft#189]
This is crucial for algorithms to prevent enhancing noise during iterative reconstruction

**Comment by paquiteau** [comment]
why not just use `density=None` ? 

If you want o only apply once, you can still get the density vector from the functions in `mrinufft.density` and apply it manually whenever its needed (ie at the first iteration for instance)

**Comment by chaithyagr** [comment]
Still needs support for gpunufft, I'm working on it don't worry
