### ISSUE TITLE
Add PROPELLER/BLADE trajectory

### ISSUE THREAD

**Issue by paquiteau** [mind-inria/mri-nufft#48]
Adding Propeller trajectories would be a nice addition to the current collection. Also this might requires some additional reconstruction methods to benefit from the motion correction.

References: 
- https://www.ajronline.org/doi/10.2214/AJR.07.3657
- https://mriquestions.com/propellerblade.html

**Comment by Daval-G** [comment]
The trajectory has been added in PR #56
