### ISSUE TITLE
Add 3D-REPI

### ISSUE THREAD

**Issue by paquiteau** [mind-inria/mri-nufft#49]
Another non-cartesian trajectory that has some nice properties

An example: 
![image](https://github.com/mind-inria/mri-nufft/assets/77174042/3f2ea49d-6a02-403c-a633-c302ce79229a)

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8616809/

**Comment by Daval-G** [comment]
Both 3D-REPI and TURBINE (from issue #50) are quite simple to implement except for one question: How should we handle split readouts ? EPI-like trajectories are characterized by blips/short transition between each line composing a single long shot. For example, the blue lines above are acquired over only one TR, but transitions between each line/spiral is not shown and could have an arbitrary duration depending on the sequence. To me it leads to two possible propositions:
1) In the trajectory initialization, we request a bunch of additional parameters for each EPI-like trajectory about how many points should be used for the transition, and we deduce the slew rate to apply in transition.
2) The EPI-like trajectories only provides lines/spirals separately but ordered implicitely as "interleaves", and we also provide a utilitary function for the user to transform those interleaves into single shots, as it would typically be used for GRE-like acquisitions. It could also be used on other trajectories that are naturally interleaved.

I prefer the second solution, it makes trajectory initialization much lighter and invite to the development of different blip/transition strategies. WDYT ?
In both cases, we will provide additional gradient manipulation techniques to create transitions, but also prewind & rewind gradients.

**Comment by paquiteau** [comment]
I like the 2nd proposal a lot! Those considerations are only relevant when using the trajectories on the scanner, so providing the idealized trajectory (as it would be used in NUFFT operator initialization) and the way to make it hardware-compatible by having proper blips is probably the best way to go (and generalize well as you mention). 

I look forward to seeing your implementations!
