### ISSUE TITLE
Add TURBINE trajectory

### ISSUE THREAD

**Issue by paquiteau** [mind-inria/mri-nufft#50]
Presented in: 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9546489/

This is not equivalent to a stack of 2D-radial trajectory due to the interleaving of the blades (see figure)

![image](https://github.com/mind-inria/mri-nufft/assets/77174042/0a33e626-3e41-4e68-a1b5-d4b2413a23ca)

**Comment by Daval-G** [comment]
From my current understanding, this pattern is extremely similar to 3D-REPI and therefore I plan to deliver both under the same PR. See issue #49 on 3D-REPI for common details.
