### ISSUE TITLE
Fix theme in readme for code?

### ISSUE THREAD

**Issue by chaithyagr** [mind-inria/mri-nufft#88]
The current python code in README is a bit off-putting, I wonder why. Documenting the issue here so that we fix it:

Here is an image, notice the underline and pretty much no color theme:

![image](https://github.com/mind-inria/mri-nufft/assets/8596659/dbcd69f5-5f80-49ce-b3c1-874ea6016e0d)

**Comment by paquiteau** [comment]
It seems that the issue is on github side: https://github.com/orgs/community/discussions/86715

A solution would be to rewrite the readme in Markdown (instead of .rst) but that would also require some update on the doc setup as well.
